apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: frontend
        image: jaicswamy962/frontend:v1
        ports:
        - containerPort: 80

  

